version: '3.3'

services:
  mysql:
    image: mysql:8.0.23
    platform: linux/amd64
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./services/mysql-db/data:/var/lib/mysql:rw,cached
    ports:
      - 3307:3306

  youtubeapi:
    build: . #path to the root project folder
    # command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/app/
    ports:
      - 8001:8001 # sets the port that maps to internal port in docker container
    links:
      - mysql
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - mysql
      - redis


  celery:
    build: .
    command: celery --app main worker --loglevel=INFO # Command used to start the Celery worker in the Docker container
    volumes:
      - .:/app
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      # depends on show that celery worker service requires the web service and the redis service to run
    depends_on:
      - web
      - mysql
      - redis

  redis:
    image: redis:alpine