# Generated by Django 4.0.2 on 2022-03-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apivideos',
            name='channel_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='apivideos',
            name='video_id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='apivideos',
            index=models.Index(fields=['title'], name='api_apivide_title_cd214e_idx'),
        ),
        migrations.AddIndex(
            model_name='apivideos',
            index=models.Index(fields=['description'], name='api_apivide_descrip_4962c2_idx'),
        ),
        migrations.AddIndex(
            model_name='apivideos',
            index=models.Index(fields=['published_at'], name='api_apivide_publish_56cd62_idx'),
        ),
    ]
